services:

  backend:
    build: ../BackEnd
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      DB_URL: jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require
      DB_USER: postgres.lclmkuhlwujdhujrwaus
      DB_PASSWORD: tAPFl5Urya67N8gc
      WAREHOUSE_ADDRESS: "Lagervej 1, 2600 Glostrup"

  frontend:
    build: .
    ports:
      - "8081:80"
    depends_on:
      - backend
